[package]
name = "rust-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
futures-util = "0.3.31"
tokio = {version = "1.44.2", features = ["rt-multi-thread"]}
tokio-stream = "0.1.17"

rand = "0.9.0"
reqwest = "0.12.15"
scraper = "0.23.1"


